export function arrayToObject(item) {
  const key = Object.keys(item)[0];
  const result = {};
  result[key] = item[key];
  return result;
}

/*
  Simple function that replaces several custom xml tags generated by eZ with html.
*/
export function replaceXmlTagsWithHtml(match, tag, keyWord) {
  switch (keyWord) {
    case 'header': return `${tag}h2`;
    case 'link': return `${tag}a`;
    case 'break': return `${tag}br`;
    default: return `${tag}${keyWord.substring(0, 1)}`;
  }
}
